### ISSUE TITLE
在 musl 环境下无法启动

### ISSUE THREAD

**Issue by madoka773** [gmg137/netease-cloud-music-gtk#269]
OS: Void linux x86_64-musl

在glibc的系统里是好的，但是在musl没法启动。

```
[five@void ~]$ RUST_BACKTRACE=full netease-cloud-music-gtk4 
thread 'main' panicked at src/main.rs:40:10:
Unable to set the text domain encoding: Os { code: 17, kind: AlreadyExists, message: "File exists" }
stack backtrace:
   0:     0x5639a4a3778c - <unknown>
   1:     0x5639a4a6154b - <unknown>
   2:     0x5639a4a33dce - <unknown>
   3:     0x5639a4a37575 - <unknown>
   4:     0x5639a4a38bf4 - <unknown>
   5:     0x5639a4a38913 - <unknown>
   6:     0x5639a4a3919f - <unknown>
   7:     0x5639a4a39091 - <unknown>
   8:     0x5639a4a37cb6 - <unknown>
   9:     0x5639a4a38db2 - <unknown>
  10:     0x5639a3cd12d5 - <unknown>
  11:     0x5639a3cd18a3 - <unknown>
  12:     0x5639a3d572ed - <unknown>
  13:     0x5639a3eeb15f - <unknown>
  14:     0x5639a3f0036b - <unknown>
  15:     0x5639a3e47d8e - <unknown>
  16:     0x5639a3e50d01 - <unknown>
  17:     0x5639a4a2db13 - <unknown>
  18:     0x5639a3e50cda - <unknown>
  19:     0x5639a3eeb45e - <unknown>
  20:     0x7f1b5120bffb - libc_start_main_stage2
                               at ./src/env/__libc_start_main.c:94:2

```

**Comment by madoka773** [comment]
```
[five@void ~]$ RUST_LOG=debug netease-cloud-music-gtk4
[2024-01-03T06:59:25Z DEBUG netease_cloud_music_gtk4::path] 初始化数据目录: "/home/five/.local/share/netease-cloud-music-gtk4"
[2024-01-03T06:59:25Z DEBUG netease_cloud_music_gtk4::path] 初始化配置目录: "/home/five/.config/netease-cloud-music-gtk4"
[2024-01-03T06:59:25Z DEBUG netease_cloud_music_gtk4::path] 初始化缓存目录: "/home/five/.cache/netease-cloud-music-gtk4"
[2024-01-03T06:59:25Z DEBUG netease_cloud_music_gtk4::path] 初始化歌词目录: "/home/five/.lyrics"
thread 'main' panicked at src/main.rs:40:10:
Unable to set the text domain encoding: Os { code: 17, kind: AlreadyExists, message: "File exists" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by madoka773** [comment]
真爱生命，远离musl
